// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotlightBDA.Data;

#nullable disable

namespace SpotlightBDA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotlightBDA.Data.CheckLimitPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndString")
                        .HasColumnType("text");

                    b.Property<int?>("FileProcessPolicyId")
                        .HasColumnType("integer");

                    b.Property<string>("Find")
                        .HasColumnType("text");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("StartString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileProcessPolicyId");

                    b.ToTable("CheckLimitPolicies");
                });

            modelBuilder.Entity("SpotlightBDA.Data.FileProcessPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileProcessPolicies");
                });

            modelBuilder.Entity("SpotlightBDA.Data.FolderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FolderData");
                });

            modelBuilder.Entity("SpotlightBDA.Data.ReplacePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FileProcessPolicyId")
                        .HasColumnType("integer");

                    b.Property<string>("FindDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FindValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Replace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileProcessPolicyId");

                    b.ToTable("ReplacePolicies");
                });

            modelBuilder.Entity("SpotlightBDA.Data.SpecialCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialCharacters");
                });

            modelBuilder.Entity("SpotlightBDA.Data.CheckLimitPolicy", b =>
                {
                    b.HasOne("SpotlightBDA.Data.FileProcessPolicy", null)
                        .WithMany("CheckLimitPolicies")
                        .HasForeignKey("FileProcessPolicyId");
                });

            modelBuilder.Entity("SpotlightBDA.Data.ReplacePolicy", b =>
                {
                    b.HasOne("SpotlightBDA.Data.FileProcessPolicy", null)
                        .WithMany("ReplacePolicies")
                        .HasForeignKey("FileProcessPolicyId");
                });

            modelBuilder.Entity("SpotlightBDA.Data.FileProcessPolicy", b =>
                {
                    b.Navigation("CheckLimitPolicies");

                    b.Navigation("ReplacePolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
